### ISSUE TITLE
Provide PAT Required Scopes

### ISSUE THREAD

**Issue by sheldonhull** [djedje72/vsts-chrome-extension#30]
I can't find any docs that specify the permissions required from the personal access token.
The question mark hover doesn't work in the setup page. 

Please consider specifying this on the setup page.

**Comment by mmangelsdorf** [comment]
Just noticed that the needed permissions (Azure calls them "scopes") are listed on the OAuth sign-in page, so I set up my PAT with them and it worked 🎉 

These are the required scopes ([PR to update readme accordingly](https://github.com/djedje72/azure-devops-chrome-extension/pull/35)):
```
Code (Read)
Graph (Read)
Identity (Read)
Project and Team (Read)
```

**Comment by djedje72** [comment]
resolved by https://github.com/djedje72/azure-devops-chrome-extension/pull/35
